name: Push latest version to DockerHub

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - ".github/workflows/release.yml"
      - "scripts/version_validation.sh"

jobs:
  dockerhub-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - PYTHON_VERSION: "3.9.5"
            DOCKERFILE_PATH: Dockerfile
    env:
      PIP_NO_CACHE_DIR: 0
      DOCKER_TAG: unfor19/frigga:latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "{{ matrix.PYTHON_VERSION }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: Build Docker Image
        run: |
          echo -n 99.99.99 > ./version
          docker build . --file "${{ matrix.DOCKERFILE_PATH }}" --tag "${DOCKER_TAG}" --build-arg GITHUB_SHA=$GITHUB_SHA
      - name: Test - Deploy Stack
        env:
          FRIGGA_TESTING: true
        run: bash docker-compose/deploy_stack.sh
      - name: Test - Apply Changes
        run: bash docker-compose/apply_changes.sh
      - name: Push to DockerHub
        run: |
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push "${DOCKER_TAG}" && echo "Pushed $DOCKER_TAG"
